apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-server
spec:
  selector:
    matchLabels:
      app: hello-server
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-server
    spec:
      containers:
      - name: hello-server
        image: hello-server:v1
        ports:
        - containerPort: 8080
        env:
          - name: SERVER_PORT
            value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: hello-server
spec:
  type: NodePort
  selector:
    app: hello-server
  ports:
    - port: 80
      targetPort: 8080
